# Generated by Django 5.2.8 on 2025-11-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('customer_id', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('product_category', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price_per_unit', models.FloatField()),
                ('total_amount', models.FloatField()),
            ],
        ),
    ]
